version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.16.3
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
jobs:
  build:
    working_directory: ~/balloon
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - save_modules
      - run:
          name: type-check
          command: yarn type-check
      - run:
          name: lint
          command: yarn lint
  test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: unit test
          command: yarn test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
